# Generated by Django 4.1.5 on 2023-01-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('slug', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=1000, null=True)),
                ('display', models.BooleanField(default=None)),
            ],
        ),
    ]
